name: Build Storybook and deploy to Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build components 🔧
        run: |
          npm ci
      # TODO not needed to build after install? npm run build
      # TODO - name: Validate ☑️
      #   run: npm run validate
      #   env:
      #     CI: false # true -> fails on warning
      - name: Build Storybook 📚
        run: |
          npm run docs:json
          npx nx run demo:build-storybook
      - name: Upload Pages artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/storybook/demo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v4
      # - name: Build Portfolio Micro App
      #   run: npx nx run portfolio:build
      # - name: Deploy Portfolio Micro App 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     token: ${{ secrets.ACCESS_TOKEN }} # Access token from the Prod repo, set in Settings > Secrets
      #     repository-name: code-star/nx-reference-portfolio
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: dist/apps/portfolio # The folder the action should deploy.
      #     clean: true # Automatically remove deleted files from the deploy branch
      # - name: Build Shell Micro App
      #   run: npx nx run demo:build
      # - name: Deploy Shell Micro App 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     token: ${{ secrets.ACCESS_TOKEN }} # Access token from the Prod repo, set in Settings > Secrets
      #     repository-name: code-star/nx-reference-shell
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: dist/apps/demo # The folder the action should deploy.
      #     clean: true # Automatically remove deleted files from the deploy branch
